### ISSUE TITLE
Franz Dark - installation - can't add services

### ISSUE THREAD

**Issue by alapo** [MikeDabrowski/franz#1]
Sorry I could not open an issue in the Franz Dark Project. I wanted to message you privately but could not find an email. I downloaded your compiled Dark Version of Franz and it might be on my end but I found some bugs. Below are detailed notes. Happy to post it on the issue 49 PR post but seemed more appropriate to private message.

If fixed I would be happy to make another video like this showing detailed installation steps which might make your version more popular among less code oriented users such as myself.

[![Franz Dark](https://img.youtube.com/vi/vQ34I4NBqpg/0.jpg)](https://www.youtube.com/watch?v=vQ34I4NBqpg)

**Comment by MikeDabrowski** [comment]
@alapo 
I updated 5.0.0-beta.19 release here https://github.com/MikeDabrowski/franz/releases/tag/v5.0.0-beta.19
It has the same number because I cleaned up repository, and made nice commits and even updated changelog, so I wanted to keep numbering in order. 
Also please make sure to get me that console screenshot of when you can't add service.

**Comment by alapo** [comment]
> @alapo
> I updated 5.0.0-beta.19 release here https://github.com/MikeDabrowski/franz/releases/tag/v5.0.0-beta.19
> It has the same number because I cleaned up repository, and made nice commits and even updated changelog, so I wanted to keep numbering in order.
> Also please make sure to get me that console screenshot of when you can't add service.

Hey Mike I sent it to you in an email but here is a copy. I will try the new version right now


Hi Mike,

Thanks for the quick response. As you requested the dev console screenshots are below. I also uploaded a new video that has more details.
[![Franz Dark](https://img.youtube.com/vi/WAt9JBGqaUo/0.jpg)](https://www.youtube.com/watch?v=WAt9JBGqaUo)

Let me know if you prefer to communicate via email or if you would like me to post it under "Issues" under your fork on GitHub. 

Although I am not code-oriented enough to help with some aspects I would be more than happy to provide a guide and help in any other way you deem fit (e.g. Documentation/Guides)

DevConsole - Before Importing Recipes
https://i.imgur.com/iusgOby.png

DevConsole - After Importing Missing Recipes
https://i.imgur.com/Q47MFP8.png

**Comment by alapo** [comment]
The newest release fixes the issue with adding services and also fixes the weirdness that was occurring with Gmail. Messenger still does not appear to function with dark theme. As usual, below is a video in case it helps. Could this be related to Application Background image? 

[![Franz Dark 3](https://img.youtube.com/vi/-97ERXjbOuc/0.jpg)](https://www.youtube.com/watch?v=-97ERXjbOuc)

I should also mention that at the moment the Transparent theme is only working on the sidebar and Menu bar. It does not seem to function on the main body of the app (at least for services I use which are Messenger, Gmail, Steam, WhatsApp, Hangouts, GitHub and Skype). I believe that Gmail is only showing a black background because I selected it from the drop-down menu in [Gmail themes](https://support.google.com/mail/answer/112508?hl=en)

Image of Transparent mode
https://i.imgur.com/Vo42u5v.png
![Transparent Mode](https://i.imgur.com/Vo42u5v.png)

**Comment by MikeDabrowski** [comment]
The theme you can select in Franz setting apply only to Franz itself that is sidebar topbar and settings menu. All other PRs are similar. 

If you want to have every service dark you have to look for dark services, there are a couple somewhere on GitHub.

Application background works only with transparent theme because of obvious reason - you need to see through. In my other repo with transparent services there is instruction how to add them. Have you tried that already? Perhaps I should enable that setting only when transparent mode is selected... 

Thank you for your time and I videos and not giving up :)

**Comment by alapo** [comment]
Thanks for your help. I will get to work on some videos this weekend. I will also show how to add your own CSS (it got asked a bunch in the forums). I have one final question if you would not mind entertaining it. I am not fully versed in CSS but I was curious why stylesheets with variable declarations [such as this one](https://userstyles.org/styles/142096/dark-whatsapp-theme-by-mew) won't work when added as a CSS. 

![CSS sheet](https://i.imgur.com/CcYA3aE.png)

**Comment by MikeDabrowski** [comment]
I think it might be platform specific. What you attached above is perhaps taken from userstyles.org. Stylus or original app might have parsed that ok, but in general css doesn't have this syntax. /* */ is just a comment so it is omitted.
If you are working on theming other apps you use I'd be happy to see PR with your changes. I'm just finishing #2 so you can start from there ;)

**Comment by alapo** [comment]
Sounds good I figured out the issues with CSS styles. It was not based on the /* */ comments. I will make a post in the coming weeks to show others how to do it if they would like to. I just got it mostly working for WhatsApp.

**Comment by MikeDabrowski** [comment]
Sure, take look at my themed recipes, I updated readme. You can add your versions for other apps.
I'm currently fighting with slack - doesn't load themes ...

**Comment by MikeDabrowski** [comment]
@alapo can we close this issue now ?

**Comment by MikeDabrowski** [comment]
Closing due to no reaction
